NotQuiteHuman/Models/Race.cs
using System;
using System.ComponentModel.DataAnnotations;
namespace NotQuiteHuman.Models
{
    public class Race
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public int AbilityScoreBonusId { get; set; }       
        public string Size { get; set; }
        public int WalkSpeed { get; set; }
        public int SwimSpeed { get; set; }
        public int FlySpeed { get; set; }
        public int ClimbSpeed { get; set; }
        [Required]
        public string CreatureType { get; set; }      


        public AbilityScoreBonus AbilityScoreBonus { get; set; }
    }
}

NotQuiteHuman/ViewModels/CreateRaceViewModel.cs
using NotQuiteHuman.Models;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace NotQuiteHuman.ViewModels
{
    public class CreateRaceViewModel
    {
        [Required]
        public string Name { get; set; }
        public string Size { get; set; }
        public int WalkSpeed { get; set; }
        public int SwimSpeed { get; set; }
        public int FlySpeed { get; set; }
        public int ClimbSpeed { get; set; }
        [Required]
        public string CreatureType { get; set; }
        public int Str { get; set; }
        public int Dex { get; set; }
        public int Con { get; set; }
        public int Int { get; set; }
        public int Wis { get; set; }
        public int Cha { get; set; }
    }
}

NotQuiteHuman/ViewModels/DeleteRaceViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using NotQuiteHuman.Models;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace NotQuiteHuman.ViewModels
{
    public class DeleteRaceViewModel
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string Size { get; set; }
        public int WalkSpeed { get; set; }
        public int SwimSpeed { get; set; }
        public int FlySpeed { get; set; }
        public int ClimbSpeed { get; set; }
        [Required]
        public string CreatureType { get; set; }
        public int Str { get; set; }
        public int Dex { get; set; }
        public int Con { get; set; }
        public int Int { get; set; }
        public int Wis { get; set; }
        public int Cha { get; set; }     
        public Language Language1 { get; set; }
        public Language Language2 { get; set; }
        public Language Language3 { get; set; }
        public Trait Trait1 { get; set; }
        public Trait Trait2 { get; set; }
        

    }
}

NotQuiteHuman/ViewModels/EditRaceViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using NotQuiteHuman.Models;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace NotQuiteHuman.ViewModels
{
    public class EditRaceViewModel
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string Size { get; set; }
        public int WalkSpeed { get; set; }
        public int SwimSpeed { get; set; }
        public int FlySpeed { get; set; }
        public int ClimbSpeed { get; set; }
        [Required]
        public string CreatureType { get; set; }
        public int Str { get; set; }
        public int Dex { get; set; }
        public int Con { get; set; }
        public int Int { get; set; }
        public int Wis { get; set; }
        public int Cha { get; set; }
        public SelectList Languages { get; set; }
        public int Language1Id { get; set; }
        public int Language2Id { get; set; }
        public int Language3Id { get; set; }
        public int SelectedTrait1Id { get; set; }
        public int SelectedTrait2Id { get; set; }
        public SelectList Traits { get; set; }

    }
}

NotQuiteHuman/Controllers/RaceController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NotQuiteHuman.Data;
using NotQuiteHuman.Models;
using NotQuiteHuman.ViewModels;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace NotQuiteHuman.Controllers
{
    public class RaceController : Controller
    {
        private readonly NotQuiteHumanContext _context;
        public RaceController(NotQuiteHumanContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            RaceOverviewViewModel viewModel = new RaceOverviewViewModel()
            {
                //Race overview Page
                Races = _context.Races.ToList(),
                AbilityScoreBonuses = _context.AbilityScoreBonus.ToList()

            };
            return View(viewModel);
        }
        public IActionResult DeleteRace(int? id)
        {
            //Delete Race page
            if (id == null) { return NotFound(); }
            Race race = _context.Races.Where(x => x.Id == id).Include(x => x.AbilityScoreBonus).FirstOrDefault();
            if (race == null) { return NotFound(); }
            DeleteRaceViewModel viewModel = new DeleteRaceViewModel()
            {               
                Language1 = _context.RaceLanguages.Where(x=>x.RaceId== race.Id).Include(x => x.Language).ToList()[0].Language,
                Language2 = _context.RaceLanguages.Where(x=>x.RaceId== race.Id).Include(x => x.Language).ToList()[1].Language,
                Language3 = _context.RaceLanguages.Where(x=>x.RaceId== race.Id).Include(x => x.Language).ToList()[2].Language,
                Trait1 = _context.RaceTraits.Where(x=>x.RaceId== race.Id).Include(x => x.Trait).ToList()[0].Trait,
                Trait2 = _context.RaceTraits.Where(x=>x.RaceId== race.Id).Include(x => x.Trait).ToList()[1].Trait,
                Id = race.Id,
                Name = race.Name,
                Size = race.Size,
                WalkSpeed = race.WalkSpeed,
                SwimSpeed = race.SwimSpeed,
                ClimbSpeed = race.ClimbSpeed,
                FlySpeed = race.FlySpeed,
                CreatureType = race.CreatureType,
                Str = race.AbilityScoreBonus.Strength,
                Dex = race.AbilityScoreBonus.Dexterity,
                Int = race.AbilityScoreBonus.Intelligence,
                Con = race.AbilityScoreBonus.Constitution,
                Wis = race.AbilityScoreBonus.Wisdom,
                Cha = race.AbilityScoreBonus.Charisma

            };
            return View(viewModel);
        }
        [HttpPost, ActionName("DeleteRace")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteRaceConfirm(int id)
        {
            //Delete race Action
            Race race = await _context.Races.FindAsync(id);
            _context.Races.Remove(race);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        public IActionResult EditRace(int? id)
        {
            //Edit Race Page
            if (id == null) { return NotFound(); }
            Race race = _context.Races.Where(x => x.Id == id).Include(x=>x.AbilityScoreBonus).FirstOrDefault();
            if (race == null) { return NotFound(); }
            EditRaceViewModel viewModel = new EditRaceViewModel()
            {
                Languages = new SelectList(_context.Languages.ToList(), "Id", "Name"),
                Traits = new SelectList(_context.Traits.ToList(), "Id", "Name"),
                //Sets the Id's for language and Traits but not the current Item
                Language1Id = _context.RaceLanguages.Where(x=>x.RaceId == id).ToList()[0].Id ,
                Language2Id = _context.RaceLanguages.Where(x => x.RaceId == id).ToList()[1].Id,
                Language3Id = _context.RaceLanguages.Where(x => x.RaceId == id).ToList()[2].Id,
                SelectedTrait1Id = _context.RaceTraits.Where(x=>x.RaceId == id).ToList()[0].Id,
                SelectedTrait2Id = _context.RaceTraits.Where(x=>x.RaceId == id).ToList()[1].Id,
                Id = race.Id,
                Name = race.Name,
                Size = race.Size,
                WalkSpeed = race.WalkSpeed,
                SwimSpeed = race.SwimSpeed,
                ClimbSpeed = race.ClimbSpeed,
                FlySpeed = race.FlySpeed,
                CreatureType = race.CreatureType,
                Str = race.AbilityScoreBonus.Strength,
                Dex = race.AbilityScoreBonus.Dexterity,
                Int = race.AbilityScoreBonus.Intelligence,
                Con = race.AbilityScoreBonus.Constitution,
                Wis = race.AbilityScoreBonus.Wisdom,
                Cha = race.AbilityScoreBonus.Charisma

            };
            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditRace(EditRaceViewModel viewModel)
        {
            //Edit Race action
            if (ModelState.IsValid)
            {
                AbilityScoreBonus abilityScoreBonus = new AbilityScoreBonus()
                {
                    Strength = viewModel.Str,
                    Dexterity = viewModel.Dex,
                    Constitution = viewModel.Con,
                    Intelligence = viewModel.Int,
                    Wisdom = viewModel.Wis,
                    Charisma = viewModel.Cha
                };
                AbilityScoreBonus abilityScoreBonusCheck = _context.AbilityScoreBonus.Where(c => c.Dexterity == abilityScoreBonus.Dexterity
                && c.Constitution == abilityScoreBonus.Constitution
                && c.Intelligence == abilityScoreBonus.Intelligence
                && c.Wisdom == abilityScoreBonus.Wisdom
                && c.Charisma == abilityScoreBonus.Charisma).FirstOrDefault();
                if (abilityScoreBonusCheck == null)
                {
                    _context.Add(abilityScoreBonus);
                    await _context.SaveChangesAsync();
                }
                
                    _context.Update(new Race()
                    {
                        Id= viewModel.Id,
                        Name = viewModel.Name,
                        Size = viewModel.Size,
                        AbilityScoreBonusId = _context.AbilityScoreBonus.Where(c => c.Dexterity == abilityScoreBonus.Dexterity
                            && c.Constitution == abilityScoreBonus.Constitution
                            && c.Intelligence == abilityScoreBonus.Intelligence
                            && c.Wisdom == abilityScoreBonus.Wisdom
                            && c.Charisma == abilityScoreBonus.Charisma).FirstOrDefault().Id,
                        WalkSpeed = viewModel.WalkSpeed,
                        SwimSpeed = viewModel.SwimSpeed,
                        ClimbSpeed = viewModel.ClimbSpeed,
                        FlySpeed = viewModel.FlySpeed,
                        CreatureType = viewModel.CreatureType
                    });
                    await _context.SaveChangesAsync();
                    //Check if exists not implemented

                    _context.Add(new RaceLanguage()
                    {
                        RaceId = viewModel.Id,
                        LanguageId = viewModel.Language1Id
                    });

                    _context.Add(new RaceLanguage()
                    {
                        RaceId = viewModel.Id,
                        LanguageId = viewModel.Language2Id
                    });
                    _context.Add(new RaceLanguage()
                    {
                        RaceId = viewModel.Id,
                        LanguageId = viewModel.Language3Id
                    });
                    _context.Add(new RaceTrait()
                    {
                        RaceId = viewModel.Id,
                        TraitId = viewModel.SelectedTrait1Id
                    });
                    _context.Add(new RaceTrait()
                    {
                        RaceId = viewModel.Id,
                        TraitId = viewModel.SelectedTrait2Id
                    });
                    await _context.SaveChangesAsync();
                


                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }
        public IActionResult CreateRace()
        {
            //Create race page
            CreateRaceViewModel viewModel = new CreateRaceViewModel()
            {                              
                Languages = new SelectList( _context.Languages.ToList(), "Id", "Name"),
                Traits = new SelectList(_context.Traits.ToList(), "Id", "Name")
                
            };         
            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateRace(CreateRaceViewModel viewModel)
        {
            //Create Race Function
            if (ModelState.IsValid)
            {
                //Check for Existing Abilityscorebonus
                AbilityScoreBonus abilityScoreBonus = new AbilityScoreBonus()
                {
                    Strength = viewModel.Str,
                    Dexterity = viewModel.Dex,
                    Constitution = viewModel.Con,
                    Intelligence = viewModel.Int,
                    Wisdom = viewModel.Wis,
                    Charisma = viewModel.Cha
                };
                AbilityScoreBonus abilityScoreBonusCheck = _context.AbilityScoreBonus.Where(c => c.Dexterity == abilityScoreBonus.Dexterity 
                && c.Constitution == abilityScoreBonus.Constitution
                && c.Intelligence == abilityScoreBonus.Intelligence
                && c.Wisdom == abilityScoreBonus.Wisdom
                && c.Charisma == abilityScoreBonus.Charisma).FirstOrDefault();

NotQuiteHuman/Views/Race/CreateRace.cshtml
@model NotQuiteHuman.ViewModels.CreateRaceViewModel
@{
    ViewData["Title"] = "Create Races";
}
<div class="row">
    <form asp-action="CreateRace" method="post" asp-method="post">
        <div class="row">

        
        <div class="row col-4">
            <div class="form-group">
                <label asp-for="Name" class="control-label">@Html.DisplayNameFor(model => this.Model.Name)</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <label asp-for="WalkSpeed" class="control-label">@Html.DisplayNameFor(model => this.Model.WalkSpeed)</label>
                <input asp-for="WalkSpeed" class="form-control" />
                <span asp-validation-for="WalkSpeed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SwimSpeed" class="control-label">@Html.DisplayNameFor(model => this.Model.SwimSpeed)</label>
                <input asp-for="SwimSpeed" class="form-control" />
                <span asp-validation-for="SwimSpeed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlySpeed" class="control-label">@Html.DisplayNameFor(model => this.Model.FlySpeed)</label>
                <input asp-for="FlySpeed" class="form-control" />
                <span asp-validation-for="FlySpeed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClimbSpeed" class="control-label">@Html.DisplayNameFor(model => this.Model.ClimbSpeed)</label>
                <input asp-for="ClimbSpeed" class="form-control" />
                <span asp-validation-for="ClimbSpeed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatureType" class="control-label">@Html.DisplayNameFor(model => this.Model.CreatureType)</label>
                <input asp-for="CreatureType" class="form-control" />
                <span asp-validation-for="CreatureType" class="text-danger"></span>
            </div>
           
        </div>
        <div class="row col-4">
             <div class="form-group">
                <label asp-for="Str" class="control-label">@Html.DisplayNameFor(model => this.Model.Str)</label>
                <input asp-for="Str" class="form-control" />
                <span asp-validation-for="Str" class="text-danger"></span>
          
                <label asp-for="Dex" class="control-label">@Html.DisplayNameFor(model => this.Model.Dex)</label>
                <input asp-for="Dex" class="form-control" />
                <span asp-validation-for="Dex" class="text-danger"></span>

                <label asp-for="Con" class="control-label">@Html.DisplayNameFor(model => this.Model.Con)</label>
                <input asp-for="Con" class="form-control" />
                <span asp-validation-for="Con" class="text-danger"></span>
            
                <label asp-for="Int" class="control-label">@Html.DisplayNameFor(model => this.Model.Int)</label>
                <input asp-for="Int" class="form-control" />
                <span asp-validation-for="Int" class="text-danger"></span>

                <label asp-for="Wis" class="control-label">@Html.DisplayNameFor(model => this.Model.Wis)</label>
                <input asp-for="Wis" class="form-control" />
                <span asp-validation-for="Wis" class="text-danger"></span>

                <label asp-for="Cha" class="control-label">@Html.DisplayNameFor(model => this.Model.Cha)</label>
                <input asp-for="Cha" class="form-control" />
                <span asp-validation-for="Cha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Size" class="control-label">@Html.DisplayNameFor(model => this.Model.Size)</label>
                <input asp-for="Size" class="form-control" />
                <span asp-validation-for="Size" class="text-danger"></span>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <select asp-for="Language1Id" asp-items="Model.Languages">
                </select>
            </div>
            <div class="form-group">
                <select asp-for="Language2Id" asp-items="Model.Languages">
                </select>
            </div>
            <div class="form-group">
                <select asp-for="Language3Id" asp-items="Model.Languages">
                </select>
            </div>
            <div class="form-group">
                <select asp-for="SelectedTrait1Id" asp-items="Model.Traits">
                </select>               
            </div>
            <div class="form-group">
                <select asp-for="SelectedTrait2Id" asp-items="Model.Traits">
                </select>
            </div>
        </div>        
        </div>
        <div class="form-group ml-2">
            <input type="submit" value="Create" class="btn" />
            <a asp-action="Index" class="btn">Back</a>
        </div>
    </form>   
</div>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
       

    }
    }

NotQuiteHuman/Views/Race/DeleteRace.cshtml
@model NotQuiteHuman.ViewModels.DeleteRaceViewModel;
@{
    ViewData["Title"] = Model.Name;
}
<div class="row">
    <table>
        <tr>
            <td>@Html.DisplayNameFor(x=>this.Model.Id)</td>
            <td>@this.Model.Id</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(x=>this.Model.Name)</td>
            <td>@this.Model.Name</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(x=>this.Model.Size)</td>
            <td>@this.Model.Size</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(x=>this.Model.WalkSpeed)</td>
            <td>@this.Model.WalkSpeed</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(x=>this.Model.FlySpeed)</td>
            <td>@this.Model.FlySpeed</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(x=>this.Model.ClimbSpeed)</td>
            <td>@this.Model.ClimbSpeed</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(x=>this.Model.ClimbSpeed)</td>
            <td>@this.Model.ClimbSpeed</td>
        </tr>
    </table>
    <table >
        <tr>
            <td>@Html.DisplayNameFor(x=>this.Model.Str)</td>
            <td>@this.Model.Str</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(x=>this.Model.Dex)</td>
            <td>@this.Model.Dex</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(x=>this.Model.Con)</td>
            <td>@this.Model.Con</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(x=>this.Model.Int)</td>
            <td>@this.Model.Int</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(x=>this.Model.Wis)</td>
            <td>@this.Model.Wis</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(x=>this.Model.Cha)</td>
            <td>@this.Model.Cha</td>
        </tr>
    </table>
    <table >
        <tr>
            <td>@Html.DisplayNameFor(x=>this.Model.Language1.Name)</td>
            <td>@this.Model.Language1.Name</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(x=>this.Model.Language2.Name)</td>
            <td>@this.Model.Language2.Name</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(x=>this.Model.Language3.Name)</td>
            <td>@this.Model.Language3.Name</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(x=>this.Model.Trait1.Name)</td>
            <td>@this.Model.Trait1.Name</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(x=>this.Model.Trait2.Name)</td>
            <td>@this.Model.Trait2.Name</td>
        </tr>      
    </table>
</div>

<form class="mt-5" asp-action="DeleteRace">
    <div class="form-group">
        <input type="submit" value="Delete" class="btn"/>
        <a asp-action="Index" class="btn" >Back</a>
    </div>
</form>

NotQuiteHuman/Views/Race/EditRace.cshtml
@model NotQuiteHuman.ViewModels.EditRaceViewModel
@{
    ViewData["Title"] = "Admin - EditRaces";
}
<div class="row">
    <form asp-action="EditRace" method="post" asp-method="post">
        <div class="row">


            <div class="row col-4">
                <div class="form-group">
                    <label asp-for="Name" class="control-label">@Html.DisplayNameFor(model => this.Model.Name)</label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="WalkSpeed" class="control-label">@Html.DisplayNameFor(model => this.Model.WalkSpeed)</label>
                    <input asp-for="WalkSpeed" class="form-control" />
                    <span asp-validation-for="WalkSpeed" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SwimSpeed" class="control-label">@Html.DisplayNameFor(model => this.Model.SwimSpeed)</label>
                    <input asp-for="SwimSpeed" class="form-control" />
                    <span asp-validation-for="SwimSpeed" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="FlySpeed" class="control-label">@Html.DisplayNameFor(model => this.Model.FlySpeed)</label>
                    <input asp-for="FlySpeed" class="form-control" />
                    <span asp-validation-for="FlySpeed" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ClimbSpeed" class="control-label">@Html.DisplayNameFor(model => this.Model.ClimbSpeed)</label>
                    <input asp-for="ClimbSpeed" class="form-control" />
                    <span asp-validation-for="ClimbSpeed" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CreatureType" class="control-label">@Html.DisplayNameFor(model => this.Model.CreatureType)</label>
                    <input asp-for="CreatureType" class="form-control" />
                    <span asp-validation-for="CreatureType" class="text-danger"></span>
                </div>

            </div>
            <div class="row col-4">
                <div class="form-group">
                    <label asp-for="Str" class="control-label">@Html.DisplayNameFor(model => this.Model.Str)</label>
                    <input asp-for="Str" class="form-control" />
                    <span asp-validation-for="Str" class="text-danger"></span>

                    <label asp-for="Dex" class="control-label">@Html.DisplayNameFor(model => this.Model.Dex)</label>
                    <input asp-for="Dex" class="form-control" />
                    <span asp-validation-for="Dex" class="text-danger"></span>

                    <label asp-for="Con" class="control-label">@Html.DisplayNameFor(model => this.Model.Con)</label>
                    <input asp-for="Con" class="form-control" />
                    <span asp-validation-for="Con" class="text-danger"></span>

                    <label asp-for="Int" class="control-label">@Html.DisplayNameFor(model => this.Model.Int)</label>
                    <input asp-for="Int" class="form-control" />
                    <span asp-validation-for="Int" class="text-danger"></span>

                    <label asp-for="Wis" class="control-label">@Html.DisplayNameFor(model => this.Model.Wis)</label>
                    <input asp-for="Wis" class="form-control" />
                    <span asp-validation-for="Wis" class="text-danger"></span>

                    <label asp-for="Cha" class="control-label">@Html.DisplayNameFor(model => this.Model.Cha)</label>
                    <input asp-for="Cha" class="form-control" />
                    <span asp-validation-for="Cha" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Size" class="control-label">@Html.DisplayNameFor(model => this.Model.Size)</label>
                    <input asp-for="Size" class="form-control" />
                    <span asp-validation-for="Size" class="text-danger"></span>
                </div>
            </div>
            <div class="col-4">
                <div class="form-group">
                    <select asp-for="Language1Id" asp-items="Model.Languages">
                    </select>
                </div>
                <div class="form-group">
                    <select asp-for="Language2Id" asp-items="Model.Languages">
                    </select>
                </div>
                <div class="form-group">
                    <select asp-for="Language3Id" asp-items="Model.Languages">
                    </select>
                </div>
                <div class="form-group">
                    <select asp-for="SelectedTrait1Id" asp-items="Model.Traits">
                    </select>
                </div>
                <div class="form-group">
                    <select asp-for="SelectedTrait2Id" asp-items="Model.Traits">
                    </select>
                </div>
            </div>
        </div>
        <div class="form-group ml-2">
            <input type="submit" value="Edit" class="btn" />
            <a asp-action="Index" class="btn">Back</a>
        </div>
    </form>
</div>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");


    }
    }

NotQuiteHuman/Views/Race/Index.cshtml
@model NotQuiteHuman.ViewModels.RaceOverviewViewModel;
@{
    ViewData["Title"] = "Races";
}
@if (this.User.Identity.IsAuthenticated)
{
    <form asp-action="CreateRace" method="get">
        <div class="form-group">
            <input type="submit" value="New Race" class="btn" />
        </div>
    </form>
}

<form asp-controller="Race" asp-action="RaceSearch" method="get">
    <div class="form-actions no-color">
        <p>
            Search
            <input asp-for="RaceSearch" />
            <input type="submit" value="search" class="btn btn-default" />
        </p>
    </div>
</form>
<table class="table table-bordered">
    <tr>
        <th>@Html.DisplayNameFor(x=>x.Races[0].Name)</th>
        <th>@Html.DisplayNameFor(x=>x.Races[0].AbilityScoreBonus.Strength)</th>
        <th>@Html.DisplayNameFor(x=>x.Races[0].AbilityScoreBonus.Dexterity)</th>
        <th>@Html.DisplayNameFor(x=>x.Races[0].AbilityScoreBonus.Constitution)</th>
        <th>@Html.DisplayNameFor(x=>x.Races[0].AbilityScoreBonus.Intelligence)</th>
        <th>@Html.DisplayNameFor(x=>x.Races[0].AbilityScoreBonus.Wisdom)</th>
        <th>@Html.DisplayNameFor(x=>x.Races[0].AbilityScoreBonus.Charisma)</th>

        @if (this.User.Identity.IsAuthenticated)
        {
            @if (User.IsInRole("admin"))
            {
                <th></th>
                <th></th>
            }
        }

    </tr>
    @if(Model.Races != null)
    {
        @foreach (var race in Model.Races)
        {
            <tr>
                <td>@race.Name</td>
                <td>@race.AbilityScoreBonus.Strength</td>
                <td>@race.AbilityScoreBonus.Dexterity</td>
                <td>@race.AbilityScoreBonus.Constitution</td>
                <td>@race.AbilityScoreBonus.Intelligence</td>
                <td>@race.AbilityScoreBonus.Wisdom</td>
                <td>@race.AbilityScoreBonus.Charisma</td>
            

                @if (this.User.Identity.IsAuthenticated)
                {
                    @if (User.IsInRole("admin"))
                    {
                        <td><a class="btn" asp-action="EditRace" asp-route-id="@race.Id">Edit</a></td>
                        <td><a class="btn" asp-action="DeleteRace" asp-route-id="@race.Id">Delete</a></td>
                    }
                }
            </tr>
        }
    }
    

</table>